using System.Text;
using System.Text.RegularExpressions;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;

namespace InterviewFlow.Core.ResumePipeline;

/// <summary>
/// DOCX → clean markdown + diagnostic raw dump (ports of
/// _extract_markdown_from_docx / _extract_text_from_docx in main.py). Byte
/// parity with the original is tested against fixtures generated by the
/// Python implementation itself. Both walks include runs inside hyperlink
/// wrappers, derive blank lines from the space-before/font-size ratio, and read
/// bullet glyphs from numbering.xml (PUA glyphs normalized to •).
/// </summary>
public static partial class DocxExtractor
{
    [GeneratedRegex(" {2,}")]
    private static partial Regex MultiSpace();

    [GeneratedRegex(@"\n{3,}")]
    private static partial Regex MultiBlank();

    private static readonly Dictionary<string, int> HeadingLevels = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Heading 1"] = 1, ["Heading 2"] = 2, ["Heading 3"] = 3,
        ["Heading 4"] = 4, ["Heading 5"] = 5, ["Heading 6"] = 6,
    };

    private sealed record StyleInfo(string Name, double? FontSizePt, double? SpaceBeforePt);

    private sealed record NumLevel(string NumFmt, string LvlText);

    private sealed class DocContext
    {
        public required Dictionary<string, StyleInfo> Styles { get; init; }
        public required Dictionary<(int NumId, int Ilvl), NumLevel> Numbering { get; init; }
        public required MainDocumentPart Main { get; init; }

        public StyleInfo? StyleFor(Paragraph p)
        {
            var id = p.ParagraphProperties?.ParagraphStyleId?.Val?.Value;
            return id is not null ? Styles.GetValueOrDefault(id) : null;
        }
    }

    private static DocContext BuildContext(WordprocessingDocument doc)
    {
        var main = doc.MainDocumentPart!;
        var styles = new Dictionary<string, StyleInfo>();
        foreach (var style in main.StyleDefinitionsPart?.Styles?.Elements<Style>() ?? [])
        {
            var id = style.StyleId?.Value;
            if (id is null)
                continue;
            var name = style.StyleName?.Val?.Value ?? id;
            // python-docx translates builtin names ("heading 1" → "Heading 1");
            // match it so style-name output and heading detection are identical.
            if (name.Length > 8 && name.StartsWith("heading ", StringComparison.Ordinal))
                name = "H" + name[1..];
            double? size = null;
            var sz = style.StyleRunProperties?.FontSize?.Val?.Value;
            if (sz is not null && double.TryParse(sz, out var half))
                size = half / 2.0;
            double? before = null;
            var spacing = style.StyleParagraphProperties?.SpacingBetweenLines?.Before?.Value;
            if (spacing is not null && double.TryParse(spacing, out var twentieths))
                before = twentieths / 20.0;
            styles[id] = new StyleInfo(name, size, before);
        }

        var numbering = new Dictionary<(int, int), NumLevel>();
        var numberingRoot = main.NumberingDefinitionsPart?.Numbering;
        if (numberingRoot is not null)
        {
            var abstractNums = numberingRoot.Elements<AbstractNum>()
                .Where(a => a.AbstractNumberId?.Value is not null)
                .ToDictionary(a => a.AbstractNumberId!.Value, a => a);
            foreach (var num in numberingRoot.Elements<NumberingInstance>())
            {
                var numId = num.NumberID?.Value;
                var absId = num.AbstractNumId?.Val?.Value;
                if (numId is null || absId is null || !abstractNums.TryGetValue(absId.Value, out var abs))
                    continue;
                foreach (var lvl in abs.Elements<Level>())
                {
                    var ilvl = lvl.LevelIndex?.Value;
                    if (ilvl is null)
                        continue;
                    numbering[(numId.Value, ilvl.Value)] = new NumLevel(
                        lvl.NumberingFormat?.Val?.InnerText ?? "bullet",
                        lvl.LevelText?.Val?.Value ?? "•");
                }
            }
        }

        return new DocContext { Styles = styles, Numbering = numbering, Main = main };
    }

    private static string NormalizeBullet(string lvlText)
    {
        if (lvlText.Length == 0)
            return "•";
        var c = lvlText[0];
        // Wingdings-style PUA glyphs → standard bullet.
        return c is >= '\uE000' and <= '\uF8FF' ? "•" : c.ToString();
    }

    private static string RunText(Run run)
    {
        var sb = new StringBuilder();
        foreach (var child in run.ChildElements)
        {
            switch (child)
            {
                case Text t:
                    sb.Append(t.Text);
                    break;
                case Break br when br.Type is null || br.Type.Value == BreakValues.TextWrapping:
                    sb.Append('\n');
                    break;
                case TabChar:
                    sb.Append('\t');
                    break;
            }
        }

        return sb.ToString();
    }

    /// <summary>Explicit true only, matching python-docx's `run.bold is True`.</summary>
    private static bool IsOn(OnOffType? prop) =>
        prop is not null && (prop.Val is null || prop.Val.Value);

    private static (bool Bold, bool Italic, bool Underline, string? Font, double? SizePt) RunProps(Run run)
    {
        var rPr = run.RunProperties;
        var bold = IsOn(rPr?.Bold);
        var italic = IsOn(rPr?.Italic);
        var underline = rPr?.Underline is { } u && (u.Val is null || u.Val.Value != UnderlineValues.None);
        var font = rPr?.RunFonts?.Ascii?.Value;
        double? size = null;
        if (rPr?.FontSize?.Val?.Value is { } sz && double.TryParse(sz, out var half))
            size = half / 2.0;
        return (bold, italic, underline, font, size);
    }

    private static IEnumerable<(Run Run, string? Url)> IterRuns(Paragraph p, DocContext ctx)
    {
        foreach (var child in p.ChildElements)
        {
            if (child is Run run)
            {
                yield return (run, null);
            }
            else if (child is Hyperlink link)
            {
                string? url = null;
                if (link.Id?.Value is { } relId)
                {
                    try
                    {
                        url = ctx.Main.HyperlinkRelationships.FirstOrDefault(r => r.Id == relId)?.Uri.OriginalString;
                    }
                    catch
                    {
                        // Broken relationship — treat as plain text.
                    }
                }

                foreach (var r in link.Elements<Run>())
                    yield return (r, url);
            }
        }
    }

    private static double FontSizePt(Paragraph p, DocContext ctx)
    {
        foreach (var (run, _) in IterRuns(p, ctx))
        {
            var (_, _, _, _, size) = RunProps(run);
            if (size is not null)
                return size.Value;
        }

        return ctx.StyleFor(p)?.FontSizePt ?? 12.0;
    }

    private static double? SpaceBeforePt(Paragraph p, DocContext ctx)
    {
        // Zero counts as absent, matching Python's falsy-length check.
        var direct = p.ParagraphProperties?.SpacingBetweenLines?.Before?.Value;
        if (direct is not null && double.TryParse(direct, out var twentieths) && twentieths != 0)
            return twentieths / 20.0;
        var styleBefore = ctx.StyleFor(p)?.SpaceBeforePt;
        return styleBefore is > 0 ? styleBefore : null;
    }

    private static void EmitSpacingBlankLines(List<string> lines, double? before, double fontSize)
    {
        if (before is null || fontSize <= 0)
            return;
        var ratio = before.Value / fontSize;
        if (ratio > 1.0)
        {
            for (var i = 0; i < Math.Ceiling(ratio); i++)
                lines.Add("");
        }
        else if (ratio > 0.5)
        {
            lines.Add("");
        }
    }

    private static string NumPrefix(Paragraph p, DocContext ctx)
    {
        var numPr = p.ParagraphProperties?.NumberingProperties;
        if (numPr is null)
            return "";
        var numId = numPr.NumberingId?.Val?.Value ?? 0;
        var ilvl = numPr.NumberingLevelReference?.Val?.Value ?? 0;
        var lvlText = ctx.Numbering.GetValueOrDefault((numId, ilvl))?.LvlText ?? "•";
        return NormalizeBullet(lvlText) + " ";
    }

    private static string Wrap(bool bold, bool italic, string text)
    {
        if (text.Trim().Length == 0 || (!bold && !italic))
            return text;
        var lead = text.Length - text.TrimStart().Length;
        var trail = text.Length - text.TrimEnd().Length;
        var inner = text.Trim();
        var marker = bold && italic ? "***" : bold ? "**" : "*";
        return text[..lead] + marker + inner + marker + (trail > 0 ? text[^trail..] : "");
    }

    // ── Clean markdown ───────────────────────────────────────────────────────

    public static string ExtractMarkdown(byte[] data)
    {
        using var stream = new MemoryStream(data);
        using var doc = WordprocessingDocument.Open(stream, isEditable: false);
        var ctx = BuildContext(doc);
        var lines = new List<string>();

        foreach (var para in doc.MainDocumentPart!.Document!.Body!.ChildElements.OfType<Paragraph>())
        {
            // Faithful-port note: the original's hyperlink URL resolution is dead
            // code (it calls part.relationships, which python-docx doesn't have,
            // and swallows the AttributeError) — so hyperlink runs always render
            // as plain text there. Match that: drop the resolved URL here. The
            // raw dump still marks (link) runs, which the original does too.
            var runItems = IterRuns(para, ctx)
                .Select(x =>
                {
                    var (bold, italic, _, _, _) = RunProps(x.Run);
                    return (Bold: bold, Italic: italic, Text: RunText(x.Run), Url: (string?)null);
                })
                .Where(x => x.Text.Length > 0)
                .ToList();

            if (!runItems.Any(x => x.Text.Trim().Length > 0))
            {
                lines.Add("");
                continue;
            }

            var styleName = ctx.StyleFor(para)?.Name ?? "Normal";
            EmitSpacingBlankLines(lines, SpaceBeforePt(para, ctx), FontSizePt(para, ctx));
            var numPrefix = NumPrefix(para, ctx);

            // Merge consecutive same-format runs, then wrap once per group.
            var bodyParts = new List<string>();
            var i = 0;
            while (i < runItems.Count)
            {
                var (bold, italic, _, url) = runItems[i];
                var text = new StringBuilder();
                while (i < runItems.Count
                       && runItems[i].Bold == bold && runItems[i].Italic == italic && runItems[i].Url == url)
                {
                    text.Append(runItems[i].Text);
                    i++;
                }

                var merged = text.ToString();
                if (url is null)
                {
                    bodyParts.Add(Wrap(bold, italic, merged));
                }
                else
                {
                    var display = merged.Trim();
                    var urlFmt = url.Contains(' ') ? $"\"{url}\"" : url;
                    var linkStr = UrlsSame(display, url) ? urlFmt : $"{Wrap(bold, italic, display)} {urlFmt}";
                    if (bodyParts.Count > 0 && bodyParts[^1].Length > 0 && !char.IsWhiteSpace(bodyParts[^1][^1]))
                        linkStr = " " + linkStr;
                    bodyParts.Add(linkStr + " ");
                }
            }

            var body = MultiSpace().Replace(string.Concat(bodyParts), " ").TrimEnd();
            var level = HeadingLevels.GetValueOrDefault(styleName, 0);
            lines.Add(level > 0 ? $"{new string('#', level)} {body.Trim()}" : $"{numPrefix}{body}");
        }

        return string.Join("\n", lines).Trim();
    }

    private static bool UrlsSame(string display, string url)
    {
        static string Norm(string s) =>
            Regex.Replace(s.Trim(), "^https?://", "").TrimEnd('/');
        return Norm(display) == Norm(url);
    }

    // ── Diagnostic raw dump ──────────────────────────────────────────────────

    public static string ExtractRaw(byte[] data)
    {
        using var stream = new MemoryStream(data);
        using var doc = WordprocessingDocument.Open(stream, isEditable: false);
        var ctx = BuildContext(doc);
        var lines = new List<string>();

        foreach (var para in doc.MainDocumentPart!.Document!.Body!.ChildElements.OfType<Paragraph>())
        {
            if (para.InnerText.Trim().Length == 0)
            {
                lines.Add("");
                continue;
            }

            var styleName = ctx.StyleFor(para)?.Name ?? "Normal";
            var fontSize = FontSizePt(para, ctx);
            var before = SpaceBeforePt(para, ctx);
            EmitSpacingBlankLines(lines, before, fontSize);

            var paraAttrs = new List<string> { styleName };
            var numPrefix = "";
            var pPr = para.ParagraphProperties;

            var leftTwips = pPr?.Indentation?.Left?.Value;
            if (leftTwips is not null && double.TryParse(leftTwips, out var twips))
            {
                var cm = twips / 567.0;
                if (Math.Round(cm, 2) > 0)
                    paraAttrs.Add($"indent={Math.Round(cm, 1).ToString(System.Globalization.CultureInfo.InvariantCulture)}cm");
            }

            if (pPr?.Justification?.Val?.InnerText is { } jc)
            {
                // python-docx reports its enum NAME ("justify") while the raw
                // OOXML token is "both" — translate for parity.
                var align = jc.ToLowerInvariant();
                paraAttrs.Add($"align={(align == "both" ? "justify" : align)}");
            }

            if (before is > 0)
                paraAttrs.Add($"before={Math.Round(before.Value)}pt");

            if (pPr?.NumberingProperties is { } numPr)
            {
                var numId = numPr.NumberingId?.Val?.Value ?? 0;
                var ilvl = numPr.NumberingLevelReference?.Val?.Value ?? 0;
                var info = ctx.Numbering.GetValueOrDefault((numId, ilvl)) ?? new NumLevel("bullet", "•");
                paraAttrs.Add($"numPr(id={numId},lvl={ilvl},fmt={info.NumFmt},char='{info.LvlText}')");
                numPrefix = NormalizeBullet(info.LvlText) + " ";
            }

            var tabs = pPr?.Tabs;
            if (tabs is not null)
            {
                var tabStrs = new List<string>();
                foreach (var tab in tabs.Elements<TabStop>())
                {
                    var val = tab.Val?.InnerText ?? "left";
                    var posLabel = tab.Position?.Value is { } pos
                        ? $"{pos / 1440.0:0.00}in"
                        : "?";
                    tabStrs.Add($"{val}@{posLabel}");
                }

                if (tabStrs.Count > 0)
                    paraAttrs.Add($"tabs=[{string.Join(", ", tabStrs)}]");
            }

            var runParts = new StringBuilder();
            foreach (var (run, url) in IterRuns(para, ctx))
            {
                var text = RunText(run);
                if (text.Length == 0)
                    continue;
                var (bold, italic, underline, font, size) = RunProps(run);
                var ra = new List<string>();
                if (url is not null)
                    ra.Add("link");
                if (bold)
                    ra.Add("bold");
                if (italic)
                    ra.Add("italic");
                if (underline)
                    ra.Add("underline");
                if (font is { Length: > 0 })
                    ra.Add($"font={font}");
                if (size is not null)
                    ra.Add($"size={Math.Round(size.Value)}pt");
                runParts.Append(ra.Count > 0 ? $"({string.Join(", ", ra)})" : "").Append(text);
            }

            lines.Add($"({string.Join(", ", paraAttrs)}) {numPrefix}{runParts}");
        }

        return string.Join("\n", lines).Trim();
    }
}
